// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// deferFunc is an autogenerated mock type for the deferFunc type
type deferFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *deferFunc) Execute() {
	_m.Called()
}

type mockConstructorTestingTnewDeferFunc interface {
	mock.TestingT
	Cleanup(func())
}

// newDeferFunc creates a new instance of deferFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newDeferFunc(t mockConstructorTestingTnewDeferFunc) *deferFunc {
	mock := &deferFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
