// Code generated by protoc-gen-svc. DO NOT EDIT.
// source: pkg/pb/rpc.proto
package pb

import "google.golang.org/grpc"

func RegisterAtMemberManagerGrpcService(s *grpc.Server, srv AtMemberManagerServer) {
	RegisterAtMemberManagerServer(s, srv)
}
